### PR TITLE
minor language cleanup

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
I am a Google employee. Looks like the auto check misses that when editing
via the web UI instead of a local client.

On Thu, Jan 21, 2016 at 8:20 AM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/pull/227#issuecomment-173566232>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by patflynn** [comment]
You might be able to configure the email address it uses for the commit
when using the web UI.

**Comment by loosebazooka** [comment]
I think you just have to include your Google email in your account settings

**Comment by patflynn** [comment]
LGTM

**Comment by elharo** [comment]
I have my google.com address in my settings , though it isn't primary

**Comment by loosebazooka** [comment]
hrm.. maybe pull down the branch and recommit the change?

**Comment by elharo** [comment]
I think I can clean this up if you add me to the repo.

**Comment by loosebazooka** [comment]
I can add you, but we don't intend on doing any more work on this.

**Pull request closed without merging**
