### PR TITLE
Rollback will use exploded war directory

### PR DESCRIPTION
**Pull request by peterfortuin**
Rollback will use exploded war directory to able to rollback when using variants (mentioned in #177)

### CODE REVIEW

**Comment by peerke** [comment]
I signed it!

**Comment by loosebazooka** [comment]
Variants haven't been built as a feature. Can you describe how you're
implementing it?

**Comment by peerke** [comment]
During the build I have a task (called replaceTokens) that replace @version@ with the version I supply to the build commando. 

In appengine-web.xml added the following:
```
...
<appengine-web-app ...>
    <version>@version@</version>
...
```

And then in my build.gradle

```
task replaceTokens(type: Copy) {
    from('src/main/webapp') {
        include '**/appengine-web.xml'
    }
    into 'build/intermediates/webapp'
    filter(ReplaceTokens, tokens: [
            version: version
    ])
    outputs.upToDateWhen { false }
}

war {
    from 'build/intermediates/webapp'
}

war.dependsOn replaceTokens
```

**Comment by peerke** [comment]
So, what the task does is making a copy of the appengine-web.xml to the build folder. During this copy I replace the version token in that file. During war building I include that appengine-web.xml again (it will override the original one that is already included from the source directory). 

The source in this pull request will make sure that a rollback will use the same appengine-web.xml that is used for deploying the app in the first place.

**Comment by peerke** [comment]
Can somebody tell me if this every going to be in?

**Comment by loosebazooka** [comment]
It is not. No major development on this plugin is expected.

**Pull request closed without merging**
