### PR TITLE
Rewire appengineFunctionalTest for faster skipping.

### PR DESCRIPTION
**Pull request by MGronber**
- appengineFunctionalTest adds appengineRun (RunTask) as a dependent
  task, so that the development server is set up for the tests to
  run. Unfortunately, RunTask is unskippable even when the tests don't
  need to be run. This wastes time during incremental builds.
- To fix, appengineFunctionalTest now disables RunTask if it intends
  to run, and then executes its Actions directly on doFirst() rather
  than letting Gradle do it. This causes RunTask to only run when the
  appengineFunctionalTest really needs it.
- Explicit invocations of appengineRun are unaffected.

TESTED:
- Developed Functional Test and ran locally:

  - In project without functional test:

    w/o patch:
    :gar:ear:appengineRun
    :gar:ear:compileFunctionalTestJava UP-TO-DATE
    :gar:ear:processFunctionalTestResources UP-TO-DATE
    :gar:ear:functionalTestClasses UP-TO-DATE
    :gar:ear:appengineFunctionalTest UP-TO-DATE

    w/ patch:
    :gar:ear:appengineRun SKIPPED
    :gar:ear:compileFunctionalTestJava UP-TO-DATE
    :gar:ear:processFunctionalTestResources UP-TO-DATE
    :gar:ear:functionalTestClasses UP-TO-DATE
    :gar:ear:appengineFunctionalTest UP-TO-DATE
    :gar:ear:appengineStop

  - In project with functional test:

    w/o patch:
    :experimental:worldserver:ear:appengineRun
    :experimental:worldserver:ear:compileFunctionalTestJava UP-TO-DATE
    :experimental:worldserver:ear:compileFunctionalTestGroovy UP-TO-DATE
    :experimental:worldserver:ear:processFunctionalTestResources UP-TO-DATE
    :experimental:worldserver:ear:functionalTestClasses UP-TO-DATE
    :experimental:worldserver:ear:appengineFunctionalTest

    w/ patch:
    :experimental:worldserver:ear:appengineRun SKIPPED
    :experimental:worldserver:ear:compileFunctionalTestJava UP-TO-DATE
    :experimental:worldserver:ear:compileFunctionalTestGroovy
    :experimental:worldserver:ear:processFunctionalTestResources UP-TO-DATE
    :experimental:worldserver:ear:functionalTestClasses
    :experimental:worldserver:ear:appengineFunctionalTest
    :experimental:worldserver:ear:appengineStop

### CODE REVIEW

**Comment by loosebazooka** [comment]
I've got an alternate implementation #164 , mind taking a look to see if it makes sense?

**Comment by MGronber** [comment]
Added comment to the alternate. It's close but because our project contains several subprojects each using the AppEngine Plugin it fails on the second subproject when it tries to modify an already executed task.

**Comment by MGronber** [comment]
Alternate LGTM. I'll close this as soon as the alternate is merged. Thanks.

**Comment by loosebazooka** [comment]
alternative merged

**Pull request closed without merging**
